networks:
  llm-db-network:
    driver: bridge
  db-network:
    driver: bridge

services:
  llm-db:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    command: start --log info --user root --pass root file:/surrealdb/surreal.db
    ports:
      - "8234:8000"
    networks:
      - llm-db-network
    volumes:
      - llm-data:/surrealdb
  db:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    command: start --log info --user root --pass root file:/surrealdb/surreal.db
    ports:
      - "7351:8000"
    networks:
      - db-network
    volumes:
      - data:/surrealdb

volumes:
  llm--data:
  data: